import type { Metadata } from "next";
import "./globals.css";
import MessageContainer from "./message_container";
import FixAutocomplete from "./fix_autocomplete";

export const metadata: Metadata = {
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body>
                {children}
                <MessageContainer />
                <FixAutocomplete />
            </body>
        </html>
    );
}
